---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

stages:
  - linter
  - build
  - deploy

# linter
shellcheck:
  stage: linter
  image: vpgrp/linter:shell
  script:
    - shellcheck build.sh
    
# build

# deploy
# EOF
