---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

.template: &build
  artifacts:
    expire_in: 1 day
    paths:
      - image
  image: docker:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay

.template: &deploy
  before_script:
    - docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
    - docker load -i image/v3.5.tar
    - docker load -i image/v3.6.tar
    - docker load -i image/v3.7.tar
    - docker load -i image/v3.8.tar
    - docker load -i image/v3.9.tar
  image: docker:latest
  only:
    - master
  services:
    - docker:dind
  stage: deploy
  variables:
    DOCKER_DRIVER: overlay


stages:
  - test
  - build
  - deploy

# test
shellcheck:
  stage: test
  image: vpgrp/linter:shell
  script:
    - shellcheck build.sh
    
# build
v3.5:
  <<: *build
  script:
    - ./build.sh -d 3.5 -v
    - mkdir image
    - docker save alpine:3.5 > image/v3.5.tar

v3.6:
  <<: *build
  script:
    - ./build.sh -d 3.6 -v
    - mkdir image
    - docker save alpine:3.6 > image/v3.6.tar

v3.7:
  <<: *build
  script:
    - ./build.sh -d 3.7 -v
    - mkdir image
    - docker save alpine:3.7 > image/v3.7.tar

v3.8:
  <<: *build
  script:
    - ./build.sh -d 3.8 -v
    - mkdir image
    - docker save alpine:3.8 > image/v3.8.tar

v3.9:
  <<: *build
  script:
    - ./build.sh -d 3.9 -v
    - mkdir image
    - docker save alpine:3.9 > image/v3.9.tar

# deploy
# EOF
