---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

.template: &build
  artifacts:
    expire_in: 1 day
    paths:
      - image
  image: vpgrp/kitchen:latest
  stage: build
  variables:
    DOCKER_DRIVER: overlay

stages:
  - linter
  - build
  - deploy

# linter
shellcheck:
  stage: linter
  image: vpgrp/linter:shell
  script:
    - shellcheck build.sh
    
# build
3dot5:
  <<: *build
  script:
    - ./build.sh -d 3.5
    - mkdir image
    - docker save alpine:3.5 > image/3.5.tar

3dot6:
  <<: *build
  script:
    - ./build.sh -d 3.6
    - mkdir image
    - docker save alpine:3.6 > image/3.6.tar

3dot7:
  <<: *build
  script:
    - ./build.sh -d 3.7
    - mkdir image
    - docker save alpine:3.7 > image/3.7.tar

3dot8:
  <<: *build
  script:
    - ./build.sh -d 3.8
    - mkdir image
    - docker save alpine:3.8 > image/3.8.tar

3dot9:
  <<: *build
  script:
    - ./build.sh -d 3.9
    - mkdir image
    - docker save alpine:3.9 > image/3.9.tar

# deploy
# EOF
